// AUTO-GENERATED FILE

export default {
  hooks: {
    useAllUserALMAmounts: () => ({}),
    useAllALMVaults: () => ({}),
    useALMVaultsByPool: () => ({}),
    useUserALMVaultsByPool: () => ({}),
    useActiveFarming: () => ({}),
    useClosedFarmings: () => ({}),
    useFarmApprove: () => ({}),
    useFarmCheckApprove: () => ({}),
    useFarmHarvest: () => ({}),
    useFarmHarvestAll: () => ({}),
    useFarmingAPR: () => ({}),
    useFarmingRewardsEarned: () => ({}),
    useFarmStake: () => ({}),
    useFarmUnstake: () => ({}),
    useLimitOrderInfo: () => ({}),
  },
  components: {
    AddALMLiquidityModal: () => null,
    AddAutomatedLiquidityButton: () => null,
    ALMPositionCard: () => null,
    CreateAutomatedPosition: () => null,
    RemoveALMLiquidityModal: () => null,
    AnalyticsPoolPage: () => null,
    AnalyticsTokenPage: () => null,
    DexCharts: () => null,
    TokensList: () => null,
    tokensColumns: () => null,
    TokensTable: () => null,
    TransactionsList: () => null,
    transactionsColumns: () => null,
    TransactionsTable: () => null,
    ActiveFarming: () => null,
    CardInfo: () => null,
    FarmingPositionCard: () => null,
    FarmingPositionImg: () => null,
    FarmTag: () => null,
    HarvestAndExitFarmingCard: () => null,
    SelectPositionFarmModal: () => null,
    KillLimitOrderModal: () => null,
    LimitOrder: () => null,
    LimitOrderButton: () => null,
    LimitOrdersList: () => null,
    LimitPriceCard: () => null,
    SwapTypeSelector: () => null,
    limitOrderColumns: () => null,
    LimitOrdersTable: () => null,
  },
  utils: {
    getRewardsCalldata: () => undefined,
    isSameRewards: () => undefined,
  },
};
