import {
  CUSTOM_POOL_DEPLOYER_BLANK,
  CUSTOM_POOL_DEPLOYER_FEE_CHANGER,
  CUSTOM_POOL_DEPLOYER_LIMIT_ORDER,
  CUSTOM_POOL_BASE,
} from "@/constants/addresses.ts";

export const customPoolDeployerTitles = {
  [CUSTOM_POOL_BASE]: "Base",
  [CUSTOM_POOL_DEPLOYER_BLANK]: "Blank",
  [CUSTOM_POOL_DEPLOYER_FEE_CHANGER]: "Fee Changer",
  [CUSTOM_POOL_DEPLOYER_LIMIT_ORDER]: "Limit Order"
};
